<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Adminmaster.Master" AutoEventWireup="true" CodeBehind="ManageUser.aspx.cs" Inherits="Home_Appliences_for__rent.Admin.ManageUser" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container-fulid">
        <div class="text-center d-flex justify-content-between">
            <h2 class="ms-5 text-uppercase" style="font-family: 'Calisto MT'; font-size: x-large; font-weight: bold; font-style: normal; font-variant: normal; text-transform: none; color: #FF6600;">RentSpace Users</h2>

            <asp:Button ID="btnExpdf" class="btn btn-outline-primary me-5" runat="server" Text="Export to PDF" OnClick="btnExpdf_Click" />
        </div>
        <hr style="border: 2px dashed red;" />
        <div class="mx-3">
            <asp:GridView ID="GvUsers" class="table table-hover table-striped table-bordered border-dark" runat="server" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateColumns="False" AutoGenerateDeleteButton="false" OnRowDeleting="GvUsers_RowDeleting" DataKeyNames="UserId">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:BoundField DataField="Userid" HeaderText="User ID" />
                    <asp:BoundField DataField="fname" HeaderText="First Name" />
                    <asp:BoundField DataField="lname" HeaderText="Last Name" />
                    <asp:BoundField DataField="email" HeaderText="Email Address" />
                    <asp:BoundField DataField="Conumber" HeaderText="Contact Number" />
                    <asp:BoundField DataField="aadhar" HeaderText="Aadhar Number" />
                    <asp:BoundField DataField="Adress" HeaderText="Address" />
                    <asp:BoundField DataField="city" HeaderText="City" />
                    <asp:BoundField DataField="zip" HeaderText="Zip" />
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:Button ID="btnDelete" class="btn btn-outline-primary" runat="server" OnClientClick="return confirm('If you delete this User, the Orders and other Informations related to it will also be deleted. Are you sure you want to delete?');" CommandName="Delete" Text="Delete" />
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" ForeColor="White" Font-Bold="True" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle ForeColor="White" HorizontalAlign="Center" BackColor="#284775" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>

        </div>
        <div class="mt-3" id="GVtoprint" runat="server">
            <asp:GridView ID="Gvusertoprint" class="table" runat="server" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateColumns="False">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:BoundField DataField="Userid" HeaderText="User ID" />
                    <asp:BoundField DataField="fname" HeaderText="First Name" />
                    <asp:BoundField DataField="lname" HeaderText="Last Name" />
                    <asp:BoundField DataField="email" HeaderText="Email Address" />
                    <asp:BoundField DataField="Conumber" HeaderText="Contact Number" />
                    <asp:BoundField DataField="aadhar" HeaderText="Aadhar Number" />
                    <asp:BoundField DataField="Adress" HeaderText="Address" />
                    <asp:BoundField DataField="city" HeaderText="City" />
                    <asp:BoundField DataField="zip" HeaderText="Zip" />
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
        </div>
    </div>
</asp:Content>
